blank_issues_enabled: false
contact_links:
  - name: a
    url: a
    about: Update Channel
  - name: a
    url: a
    about: Support Group
  - name: Bug Report Group
    url: a
    about: Bug Report & Feature Request Group
